Fix up git remote-add

diff --git a/bin/git-remote-add b/bin/git-remote-add
--- a/bin/git-remote-add
+++ b/bin/git-remote-add
@@ -4,8 +4,17 @@ if [[ -z $name ]]; then
   echo 'set name' 2>&1
   exit 1
 fi
-url="$(git remote -v | grep origin | head -1 | cut -f2 | cut -d' ' -f1 | \
-  NAME="$name" perl -F/ -ape '$F[3] = $ENV{NAME}; $_ = join "/", @F')"
+git_url="$(git remote -v | grep origin | head -1 | cut -f2 | cut -d' ' -f1)"
+if [[ $git_url =~ ^(http|git|ssh):// ]]; then
+  url="$(echo "$git_url" | \
+    NAME="$name" perl -F/ -ape '$F[3] = $ENV{NAME}; $_ = join "/", @F')"
+elif [[ $git_url =~ ^git@ ]]; then
+  url="$(echo "$git_url" | \
+    NAME=hoob3rt perl -pe '($host, $repo) = (split m|[:/@]|)[1, 3]; $_ = "https://git\@$host/$ENV{NAME}/$repo"')"
+else
+  echo "failed to parse url: $git_url" 2>&1
+  exit 1
+fi
 if [[ -z $url ]]; then
   echo "failed to set url for $name" 2>&1
   exit 1
